### ISSUE TITLE
prevent changing zoom level

### ISSUE THREAD

**Issue by ghost** [EndPointCorp/lg-peruse-a-rue#1]
We have found that zoom level can be changed if there is a mouse attached to the system and the user scrolls the mouse wheel.  We need to prevent the changing of the zoom level.
![lg-montage_mexico](https://cloud.githubusercontent.com/assets/1512670/6086953/cec36b64-ae13-11e4-90b0-4f06cc5d0292.jpg)

**Comment by kannan4k** [comment]
buenosaires montage image

![lg-montage_buenosaires](https://cloud.githubusercontent.com/assets/142576/6187764/ca95af6e-b3b0-11e4-9d1c-52cd0a79ba24.png)
