### ISSUE TITLE
Create easy way to enable/disable POI groups

### ISSUE THREAD

**Issue by ghost** [EndPointCorp/lg-peruse-a-rue#6]
Create an easy way to enable/disable POI groups.  For example, rather than having a single default-poi.json file that contains groups such as Ocean, Earth, National Parks, Art Project, you would have a separate file for each category (i.e., poi-national-parks.json, poi-ocean.json, poi-art-project.json, etc), then pick and choose which ones are specified within the config.json.  This would make it easy to enable/disable whole groups on the fly.

Another option is to have a directory called poi-enabled and one called poi-available.  Then you can have anything that is in poi-enabled get automatically enabled by default, similar to the way that lighttpd uses conf-available and conf-enabled directories.

**Comment by kannan4k** [comment]
https://github.com/EndPointCorp/lg-peruse-a-rue/commit/aa3b0467ab78d8c3168943cfc90da4bc5ede179b
